# Generated by Django 5.0.2 on 2024-03-07 02:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightobservation',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Observation Datetime'),
        ),
    ]
