# Generated by Django 5.0.2 on 2024-02-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weighttarget',
            name='name',
            field=models.CharField(default='Test', max_length=256),
            preserve_default=False,
        ),
    ]
