# Generated by Django 5.0.2 on 2024-02-18 20:28

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0002_weighttarget_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='weighttarget',
            name='value',
            field=models.DecimalField(db_comment='Target weight in kilograms', decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Weight (kg)'),
        ),
        migrations.AddConstraint(
            model_name='weighttarget',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_name_constraint'),
        ),
    ]
