# Generated by Django 5.0.2 on 2024-03-17 01:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0002_alter_weightobservation_datetime'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='weighttarget',
            name='unique_name_constraint',
        ),
        migrations.RemoveConstraint(
            model_name='weighttarget',
            name='unique_value_constraint',
        ),
        migrations.AddConstraint(
            model_name='weighttarget',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='weight_target_unique_name_constraint'),
        ),
        migrations.AddConstraint(
            model_name='weighttarget',
            constraint=models.UniqueConstraint(fields=('user', 'value'), name='weight_target_unique_value_constraint'),
        ),
    ]
