# Generated by Django 5.0.2 on 2024-02-20 02:03

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0003_alter_weighttarget_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weighttarget',
            name='value',
            field=models.DecimalField(db_comment='Target weight in kilograms', decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Weight (kg)'),
        ),
    ]
