# Generated by Django 5.0.2 on 2024-03-18 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0003_remove_weighttarget_unique_name_constraint_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weightobservation',
            options={'verbose_name': 'Weight Observation'},
        ),
    ]
