# Generated by Django 5.0.2 on 2024-02-20 09:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0005_alter_weightobservation_weight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(db_comment='Baseline weight in kilograms', decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Weight (kg)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'weight_baselines',
                'indexes': [models.Index(fields=['user'], name='weight_base_user_id_7c8326_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='weightbaseline',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_constraint'),
        ),
    ]
