# Generated by Django 5.0.2 on 2024-02-20 09:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0006_weightbaseline_weightbaseline_unique_user_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseline_weight', models.DecimalField(db_comment='Baseline weight in kilograms', decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Weight (kg)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'weight_user_info',
            },
        ),
        migrations.DeleteModel(
            name='WeightBaseline',
        ),
        migrations.AddIndex(
            model_name='userinfo',
            index=models.Index(fields=['user'], name='weight_user_user_id_80a1a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='userinfo',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_constraint'),
        ),
    ]
