# Generated by Django 5.0.2 on 2024-02-24 20:57

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0008_weighttarget_colour_alter_userinfo_baseline_weight_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weighttarget',
            options={'verbose_name': 'Weight Target'},
        ),
        migrations.RenameField(
            model_name='weightobservation',
            old_name='weight',
            new_name='value',
        ),
        migrations.AlterField(
            model_name='weighttarget',
            name='colour',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None),
        ),
    ]
