# Generated by Django 5.0.2 on 2024-03-03 20:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0009_alter_weighttarget_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='baseline_weight_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Baseline Weight Datetime'),
        ),
    ]
