# Generated by Django 5.0.2 on 2024-02-18 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='customuser',
            table_comment='User Accounts',
        ),
    ]
