# Generated by Django 5.0.2 on 2024-03-21 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_alter_componentdefinition_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.componentdefinition'),
        ),
    ]
